### PR TITLE
again updating simple-helm-toolchain for use with headless

### PR DESCRIPTION
**Pull request by maire-kehoe**
where the headless toolchain creation api is as described in:
  Headless Toolchain Creation/Update using POST
  https://github.com/open-toolchain/sdk/wiki
    /Toolchain-Creation-page-parameters
      #headless-toolchain-creationupdate-using-post

Again attempting the change that had been merged in:
- updating simple-helm-toolchain for use with headless
 https://github.com/open-toolchain/simple-helm-toolchain/pull/51

and had been reverted in:
- Revert "updating simple-helm-toolchain for use with headless (#51)"
  https://github.com/open-toolchain/simple-helm-toolchain/pull/54

### CODE REVIEW

**Review by gmarjoram — APPROVED** [review]

**Comment by maire-kehoe** [comment]
Steps to verify use of simple-helm-toolchain with the headless API

1. On the command line, log in to the ibmcloud tool, 
    and do `ibmcloud target -g default` to configure your resource group target.
2. Create a test3.sh file with the following content:
```
#!/bin/bash

echo "Starting..."

token=$(ibmcloud iam oauth-tokens | head -1 | sed 's/.*:[ \t]*//')
api_key=$(ibmcloud iam api-key-create "api-key created on $(date)" | grep "API Key" | sed 's/API Key[ ]*\([^ ]*\)[ ]*/\1/g')
resource_group_id=$(ibmcloud resource groups --output json | jq -r '.[0].id')
registry_region=$(ibmcloud cr region | grep region | sed -E "s/.+targeting region '([^']+)'.+/\1/g" | sed -E 's/(.+)/ibm:yp:\1/g')
registry_namespace=$(ibmcloud cr namespaces | grep -A 1 Namespace | grep -v Namespace | sed -E 's/([^ ]+).*/\1/g')
prod_cluster_name=$(ibmcloud ks clusters --json | grep \"name\" | head -1 | sed -E 's/.+: .(.+).,/\1/g')
prod_region=$(ibmcloud ks cluster get --cluster="${prod_cluster_name}" --json | grep region | sed -E 's/.+: .(.+).,/\1/g' | sed -E 's/(.+)/ibm:yp:\1/g')
prod_resource_group=$(ibmcloud ks cluster get --cluster="${prod_cluster_name}" --json | grep resourceGroupName | sed -E 's/.+: .(.+).,/\1/g')

host="https://cloud.ibm.com"

env_id="ibm:yp:us-south"
#env_id="ibm:yp:eu-de"
#env_id="ibm:yp:us-east"
#env_id="ibm:yp:au-syd"

template="https://github.com/open-toolchain/simple-helm-toolchain"
# branch="master"

body="autocreate=true"
body="${body}&repository=${template}"
body="${body}&env_id=${env_id}"
body="${body}&apiKey=${api_key}"
body="${body}&resourceGroupId=${resource_group_id}"
# body="${body}&appName=cccnodejswebappwithexpressjsjnhus"
# body="${body}&toolchainName=CccNodejsWebAppwithExpressjsJNHUS"
body="${body}&registryRegion=${registry_region}"
body="${body}&registryNamespace=${registry_namespace}"
body="${body}&prodRegion=${prod_region}"
body="${body}&prodResourceGroup=${prod_resource_group}"
body="${body}&prodClusterName=${prod_cluster_name}"
body="${body}&prodClusterNamespace=prod"

url="${host}/devops/setup/deploy?env_id=${env_id}"
url="${url}&repository=${template}"
# url="${url}&branch=${branch}"

echo "POST url is: $url"
echo "POST body is: $body"

echo "date is: "
date

curl -v -k -X POST \
  -H "Authorization: ${token}" \
  -H "Accept: application/json" \
  -d "${body}" \
  "${url}"


```
3. If your ibmcloud is not configured to point to the region us-south, change the env_id variable there.
4. Run that script: ./test3.sh

As expected it runs ok, and the end of the output is like:
```
< HTTP/2 302
< content-length: 0
< x-powered-by: Express
< strict-transport-security: max-age=31536000; includeSubDomains
< location: https://cloud.ibm.com/devops/toolchains/803d00c2-2e41-4670-bc68-006b144d75e4?env_id=ibm:yp:us-south
< x-frame-options: SAMEORIGIN
< expires: Thu, 10 Oct 2019 15:04:09 GMT
< cache-control: max-age=0, no-cache, no-store
< pragma: no-cache
< date: Thu, 10 Oct 2019 15:04:09 GMT
< server-timing: cdn-cache; desc=MISS
< server-timing: edge; dur=22
< server-timing: origin; dur=5414
< set-cookie: ...
< set-cookie: ...
<
* Connection #0 to host cloud.ibm.com left intact
```
6. That location line has the URL to the toolchain that was created, copy that and open it in a web browser. 
7. Open the Pipeline, and wait for the Deploy stage to finish (should be successful).
8. To open the app in the browser, you need to find the ipAddress & port. 
     To find the ipAddress, on the command line do a command like this except with your cluster name:
```
maires-mbp:scripts mkehoe$ ibmcloud ks workers --cluster mycluster
OK
ID                                                     Public IP        Private IP      Flavor   State    Status   Zone    Version
kube-bm90tg3d0dgcf5svd5bg-mycluster-default-00000056   184.172.250.57   10.76.197.129   free     normal   Ready    hou02   1.14.6_1533*

maires-mbp:scripts mkehoe$
```
   Where the value in that "Public IP" column is the ip address.
9. To find the port number, do like so with your cluster name (mcluster here) and your namespace (prod here):
```
maires-mbp:scripts mkehoe$ ibmcloud ks clusters
OK
Name        ID                     State    Created      Workers   Location   Version       Resource Group Name   Provider
mycluster   bm90tg3d0dgcf5svd5bg   normal   1 week ago   1         hou02      1.14.7_1534   default               classic
maires-mbp:scripts mkehoe$
maires-mbp:scripts mkehoe$ ibmcloud ks cluster config --cluster=mycluster
OK
The configuration for mycluster was downloaded successfully.

Added context for mycluster  to the current kubeconfig file.
You can now execute 'kubectl' commands against your cluster. For example, run 'kubectl get nodes'.
maires-mbp:scripts mkehoe$

maires-mbp:scripts mkehoe$ kubectl config current-context
mycluster/bm90tg3d0dgcf5svd5bg
maires-mbp:scripts mkehoe$
maires-mbp:scripts mkehoe$ kubectl get service -n prod
NAME                                                 TYPE       CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
nodejswebappwithexpressjsjnhus-application-service   NodePort   172.21.98.214    <none>        3000:31991/TCP   14s
prod-hello-helm-20190930153027252-hello              NodePort   172.21.249.125   <none>        80:31342/TCP     9d
prod-hello-helm-20191009145708145-hello              NodePort   172.21.219.253   <none>        80:30020/TCP     21h
maires-mbp:scripts mkehoe$
```
8. Combine the ipAddress and port to a url like: https://184.172.250.57:31991  
   and open the url in a browser.

The web page of the app should appear ok in the browser.

**Comment by maire-kehoe** [comment]
Updated above script to add `--cluster=` to ibmcloud ks commands to prevent error:
```
$ ibmcloud ks cluster get "mycluster-free" --json
FAILED
Incorrect Usage. An argument was used without a flag: 'mycluster-free'. Each argument requires a flag. To see available flags, run 'ibmcloud ks cluster get --help'.

NAME:
        get - View the details of a cluster.

USAGE:
        ibmcloud ks cluster get --cluster CLUSTER [--output OUTPUT] [-q] [--show-resources]

PARAMETERS:
    --cluster value, -c value  Specify the cluster name or ID.
    --show-resources           Show additional cluster resources such as addons, VLANs, and subnets.
    --output                   Prints the command output in the provided format. Available options: json
    -q                         Do not show the message of the day or update reminders.

$
```

**Comment by maire-kehoe** [comment]
Updated above code for `ibmcloud ks` config for kubectl
to prevent error like:
```
$ ibmcloud ks cluster config --export --cluster=mycluster-free-dev
Incorrect Usage: flag provided but not defined: -export

NAME:
        config - Download the Kubernetes configuration files and certificates to connect to your cluster by using kubectl commands.

USAGE:
        ibmcloud ks cluster config --cluster CLUSTER [--admin] [--network] [--output OUTPUT] [-q] [--skip-rbac]

PARAMETERS:
    --cluster value, -c value  Specify the cluster name or ID.
    --admin                    Retrieve administrator certificates and PEM keys.
    --network                  Retrieve the Calico network config with the Admin config.
    --skip-rbac                Skip adding RBAC roles. Include this option only if you manage your own Kubernetes RBAC roles. If you use IAM service access roles to manage all your RBAC users, do not include this option.
    --output                   Prints the command output in the provided format and skips kubeconfig merges. Available options: json, yaml, zip
    -q                         Do not show the message of the day or update reminders.

FAILED
flag provided but not defined: -export

$
```

**Comment by maire-kehoe** [comment]
Note, see the latest version of this bash script at:
- open-toolchain, sdk wiki, Toolchain Creation Page Parameters,  
   Sample script and output for simple-helm-toolchain Kubernetes Helm template
   https://github.com/open-toolchain/sdk/wiki/Toolchain-Creation-page-parameters#sample-script-and-output-for-simple-helm-toolchain-kubernetes-helm-template

**Pull request merged**
